---
title: "post_estudio"
author: "Yenibel Cuevas"
date: "25/7/2022"
output: html_document
---


```{r}
library(httr) # conectar al API
library(jsonlite) # convertir un objeto JSON a objeto R
library(ggplot2) # generar gráficos

apiKey <- "colocar tu API key"

# colocamos el url, end points y parámetros de consulta según las especificaciones 
# de la página web del API de la SB https://desarrollador.sb.gob.do/

base_url = "https://apis.sb.gob.do/estadisticas"
end_point = "/captaciones/moneda/"

result <- GET(paste0(base_url,end_point),
  add_headers("Ocp-Apim-Subscription-Key"= apiKey),
  query = list(
    periodoInicial = "2019-01",
    periodoFinal = "2021-12", 
    tipoEntidad= "TODOS"
  ),
  encode = "json"
)
```

```{r echo=TRUE}

result <- content(result, as = "text", encoding = "UTF-8") # retorna un objeto en formato JSON

result <- fromJSON(result) # convierte un objeto JSON a objeto R

df <- as.data.frame(result$data) # convierte objETO R a Data frame

print(head(df,3)) # Imprime las primeras 3 observaciones
```

Observamos que la data ha sido cargada satisfactoriamente. Ahora vamos a crear la gráfica. 
```{r}

ggplot(data=df, aes(
         fill = divisa,
         y = balance / 1000000,
         x = as.Date(paste(periodo,"-01",sep="")))) +
  scale_x_date(labels = scales::date_format("%b-%Y"), breaks = "6 month") +
  scale_y_continuous(labels = scales::comma) +
  geom_bar(position = "stack", stat = "identity") +
  labs(x = " ",
       y = " ",
       fill = " ",
       title = "Captaciones del Sistema Financiero por Moneda", 
       subtitle = paste0("enero 2019 - diciembre 2021", "\n","Valores en DOP millones")) +
  scale_fill_manual(
    values = c(
      "DÓLAR ESTADOUNIDENSE" = "5A97B3",
      "EURO" = "grey80",
      "PESO DOMINICANO" = "#0d3048")) +
  theme(
    legend.position = "top",
    legend.text = element_text(size = 7),
    panel.background = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 11 ),
    plot.subtitle = element_text(hjust = 0.5,size = 9) ) 
  
```


```{r}
fig <-
  plot_ly(
    subset(df, indicador == "Total de Activos Netos"),
    x = ~ periodo,
    y = ~ valor,
    type = 'scatter',
    mode = "lines"
  )  %>%
  layout(
    title = list(text = "Total de Activos Netos APAP", x = 0.5, xanchor = 'center'),
    xaxis = list(
      title = " ",
      tickformat = "%m-%Y",
      type = "date"
    ),
    yaxis = list(title = " ", tickformat = ",d")
  )
fig
```




